get http://localhost:3000/usuarios

###

get http://localhost:3000/usuarios/2

###

put http://localhost:3000/usuarios

###

post http://localhost:3000/usuarios
Content-Type: application/json

{
    "nombre": "Julio",
    "apellido": "Aguilar",
    "email": "julio@gmail.com"
}